# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        passport:
            uri_prefix: /userFiles/passport
            upload_destination: '%kernel.project_dir%/public/userFiles/passports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        curriculumvitae:
            uri_prefix: /userFiles/cv
            upload_destination: '%kernel.project_dir%/public/userFiles/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profilePicture:
            uri_prefix: /userFiles/profilePicture
            upload_destination: '%kernel.project_dir%/public/userFiles/profilePicture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer